# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1114PageTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "PagingKit"
  # Pods for 1114PageTest

end
